/* A777ance Operator Console — service worker.
 * Makes the console installable (PWA) and openable offline on phone and laptop.
 * Cache-first for the known app shell; network with a cache fallback for the rest.
 * GENERATED by tools/generate_console.py — bump by regenerating, not by hand. */
const CACHE = 'a777ance-console-v1';

const ASSETS = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icons/icon.svg',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-512-maskable.png',
  './icons/apple-touch-icon.png',
  './stages/brand-identity.html',
  './stages/web-presence.html',
  './stages/demand-generation.html',
  './stages/funnels-and-capture.html',
  './stages/phone-and-comms.html',
  './stages/sales-and-onboarding.html',
  './stages/statements-delivery.html',
  './stages/payments-receivables.html',
  './stages/client-list-and-crm.html',
  './stages/recruiting-and-guild.html',
  './stages/gig-workers-compliance.html',
  './stages/automations.html'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    caches.match(event.request).then((hit) => {
      if (hit) return hit;
      return fetch(event.request)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(CACHE).then((cache) => cache.put(event.request, copy));
          return resp;
        })
        .catch(() => caches.match('./index.html'));
    })
  );
});
